### ISSUE TITLE
unificar sessão www e https valedominho.com

### ISSUE THREAD

**Issue by valedominho** [valedominho/portaldigital#2]

**Comment by DrupGal** [comment]
Resolvido. Todo os pedidos non www foram reencaminhados para www com a reconfiguração do .htaccess do drupal descomentando o seguinte:

  # To redirect all users to access the site WITH the 'www.' prefix,
  # (http://example.com/foo will be redirected to http://www.example.com/foo)
  # uncomment the following:
  RewriteCond %{HTTP_HOST} .
  RewriteCond %{HTTP_HOST} !^www\. [NC]
  RewriteRule ^ http%{ENV:protossl}://www.%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
  #
