### ISSUE TITLE
Retirar opção de subscrever na taxonomia

### ISSUE THREAD

**Issue by valedominho** [valedominho/portaldigital#23]
Quando se adiciona uma taxonomia num artigo ou entity se estiver ligado a uma taxonomia aparece a opção de subscrever o que induz o utilizador em erro, sobretudo nas ações, pois parece que é a inscrição.

**Comment by fernandesj** [comment]
Retirado utilizando a opção de [Views] view/taxonomy_term/edit e em feed CONFIGURAÇÕES DO FEED
Anexar a:[Nenhum]
